### ISSUE TITLE
Update Readme: from pyjs9 import *  to  from pyjs9 import JS9

### ISSUE THREAD

**Issue by jberlanga** [ericmandel/pyjs9#4]
This is to address @cdeil 's comment in Issue #2 .

I'll go ahead and take care of it since it's an easy fix.

**Comment by jberlanga** [comment]
I wanted to try out the updated import command to make sure it works, but it seems that setting up JS9 (probably the part to do with the server-side helper) is a bit more involved than I thought.  I'm getting errors following the commands in the Readme:

> > > from pyjs9 import *
> > > dir()
> > > ['JS9', '**builtins**', '**doc**', '**name**', '**package**', 'js9Globals']
> > > j=JS9()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyjs9/**init**.py", line 199, in **init**
> > >     self._alive()
> > >   File "pyjs9/__init__.py", line 213, in _alive
> > >     self.send(None, msg="alive")
> > >   File "pyjs9/__init__.py", line 235, in send
> > >     raise IOError,  "{0}: {1}".format(self.host, e.strerror)
> > > IOError: http://localhost:2718: [Errno 111] Connection refused

Anyone else is free to take this on.

**Comment by cdeil** [comment]
Did you start the helper?
Install https://nodejs.org/, clone https://github.com/ericmandel/js9 and in a separate terminal type

```
node js9helper.js
```

It won't print anything, but then the js9helper should be running and this is needed before you can instantiate the `JS9` object for pyjs9.

**Comment by cdeil** [comment]
@jberlanga - Is this (adressing https://github.com/ericmandel/pyjs9/issues/2#issuecomment-76674029) something you're still working on and want to make a pull request?

If no, this is something that maybe @SaturnSummoner could do, she is applying for GSoC to work on pyjs9.

In any case, I think it would be good to take everything after this line https://github.com/ericmandel/pyjs9/blame/master/README.rst#L33 and put it into a new file `docs/getting_started.rst`. Working in the docs folder is a better place to expand the documentation (and eventually setting up [sphinx docs](http://sphinx-doc.org/) to get an html version that we can put on https://readthedocs.org/, but let's do one step at a time...)

**Comment by jberlanga** [comment]
@cdeil I'm not working it.  @SaturnSummoner, please feel free to take it on.
