### ISSUE TITLE
js9 and Ipython

### ISSUE THREAD

**Issue by montefra** [ericmandel/pyjs9#6]
@ericmandel: In case you are not in the ipython mailing list,.

@gijzelaerr is starting a project to use js9 into an ipython notebook.

[The first email is this one](https://mail.scipy.org/pipermail/ipython-dev/2015-October/016879.html)

**Comment by gijzelaerr** [comment]
wanted to let @ericmandel know when I had more to show than an error :)

**Comment by ericmandel** [comment]
@gijzelaerr @montefra @dfink

Hi Gijs,

This is an **extremely** important project, and comes just two days after I received email from someone visiting AstroHack and wanting just this functionality. As @montefra will confirm, my understanding of Python is pretty limited, so I have to rely on help from the Python community. But please keep me informed about progress (I'm not on any Python mailing lists as yet) and let me know if there is any way I can help (e.g. if changes have to be made to JS9). I'm totally in favor of this idea.

Thanks for starting this, it's been on my mind for a year but I just don't have the resources to do it myself.

**Comment by gijzelaerr** [comment]
We really would like to see this also, so I'll be working on this. I hope JS9 will work without any modifications.

**Comment by gijzelaerr** [comment]
so maybe you know this @ericmandel 

I can inject javascript into an IPython notebook succesfully, but somehow something goes wrong when I try to load the `js9support.js` file. Becally what happens is that I read the file in python, transfer it to the browser using IPython logic as a string. In the browser it is executed using javascript `eval()`. But somehow I get this error:

`TypeError: Cannot read property 'plugins' of undefined`

It is a bit hard to debug this, since I can't look into the code that is being executed. Do you have any idea what is going wrong?

**Comment by ericmandel** [comment]
@gijzelaerr the js9support.txt file has a list of what is contained in js9support.js and all of the files are maintained in the js subdirectory. When I grep for 'plugins', I see that it's used in jquery.flot.js:

```
        function initPlugins() {

            // References to key classes, allowing plugins to modify them

            var classes = {
                Canvas: Canvas
            };

            for (var i = 0; i < plugins.length; ++i) {
                var p = plugins[i];
                p.init(plot, classes);
                if (p.options)
                    $.extend(true, options, p.options);
            }
        }
```

But InitPlugins is called this way:

```
initPlugins(plot);
```

This looks like a bug to me: the initPlugins call should have a formal argument called "plugins". Instead, it's relying on the enclosing call's definition of plugins. 

So ... as a first step, I would load the files mentioned in js9support.txt individually and leave out all the jquery.flot.\* files and see if that works. If it does, I would add the flot files back in, after making the change above. And if that works, we can either change flot and remake js9support.js or look for an update to flot.

**Comment by ericmandel** [comment]
Or it might be that the loop has to be wrapped in:

```
    if( plugins ){
       ....
    }
```

**Comment by gijzelaerr** [comment]
Hi @ericmandel Thanks for the suggestion.

If you don't mind, I propose we move discussion to the `js9notebook` repository to not polute this repository: https://github.com/gijzelaerr/js9notebook/issues/1

**Comment by ericmandel** [comment]
@gijzelaerr @montefra Yes, good idea, I'll close this issue.
