### ISSUE TITLE
Indentation problem in __init__.py file

### ISSUE THREAD

**Issue by AyushYadav** [ericmandel/pyjs9#7]
Some return lines in functions after lines 756 have a indentation problem. All the major functions have 4 space tab but a few functions have a 3 space tab creating the error while importing the js9 package. I have fixed it. Let me know how to push it to the repo here or at the zip download from the js9 webpage.

**Comment by ericmandel** [comment]
@AyushYadav Thanks for fixing these. Do you want to make a PR?

```
https://help.github.com/articles/creating-a-pull-request/
```

If not, you could simply email me your edited file ...

Is there a tool to check for consistent indentation? I'm barely literate with Python and seem to trip over this problem continually.

**Comment by AyushYadav** [comment]
@ericmandel I will make a PR and submit it today. 
I also am looking for some auto-indentation corrector. Will inform if found soon. Thanks.

**Comment by ericmandel** [comment]
@AyushYadav That would be good, as I can't see any problems in the current code, which I am manually checking with emacs.

**Comment by AyushYadav** [comment]
@ericmandel [pycodestyle](https://pypi.python.org/pypi/pycodestyle) Is one such tool that can be used to check for indentation issues and other popular coding standards.

**Comment by ericmandel** [comment]
@AyushYadav Thanks! I installed pycodestyle, ran it as recommended in the docs:
````
pycodestyle --first __init__.py
````
and made some changes to get a clean result, all updated in GutHub.
